### ISSUE TITLE
sc.get_courses() throws error. KeyError: 'course'

### ISSUE THREAD

**Issue by GrandMoff100** [ErikBoesen/schoolopy#20] opened 2020-09-29 16:51 UTC
```py
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    courses = sc.get_courses()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/schoolopy/main.py", line 241, in get_courses
    return [Course(raw) for raw in self._get('courses')['course']]
KeyError: 'course'
```

**Comment by ErikBoesen** [comment] 2020-09-29 16:58
Duplicate of #19. This is a problem with Schoology not serving course data for some reason. I can't do anything about this unfortunately.

**Closed by ErikBoesen** 2020-09-29 16:58 UTC
Labels: duplicate

**Comment by Dwouka** [comment] 2020-11-13 19:39
this makes like half of the API useless, maybe you should put something in the readme because I just spent 2 hours using this before I noticed

**Comment by ErikBoesen** [comment] 2020-11-16 19:32
@Dwouka Thanks for the suggestion, I've added a note to the README. Please note, again, that this issue results from Schoology not providing expected data.

**Comment by gadhagod** [comment] 2021-01-30 04:59
Maybe when a `KeyError` happens or the response is blank a custom error can be thrown? This can make it easier to know exactly why it happens.

**Comment by AndrewLester** [comment] 2021-01-30 23:39
> Maybe when a `KeyError` happens or the response is blank a custom error can be thrown? This can make it easier to know exactly why it happens.

This is a good idea, I'll try implementing it.

Also, @GrandMoff100 , you may be looking for the `section` related methods rather than `course` ones. They're slightly different.
